spring:
  datasource:
    url: jdbcï¼šmysql://localhost:3306/caesar_dev
    username: caesar_dev_user
    passward: lt

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
